apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-puller-workbench
  namespace: rhods-notebooks
  labels:
    k8s-app: image-puller
spec:
  selector:
    matchLabels:
      name: image-puller
  template:
    metadata:
      labels:
        name: image-puller
    spec:
      containers:
      - name: ic-workbench
        image: quay.io/acidonpe/ocp-ai-insurance-model:1.0
        command: ["tail"]
        args: ["-f", "/dev/null"]
        resources:
          limits:
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 10Mi